name: Toolchains
on:
  push:
  pull_request:
jobs:
  c:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run
        env:
          CC: ${{ matrix.compiler }}
        run: make clean check
